version: "3.9"
services:
  db:
    image: postgres
    container_name: postgresdb
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db-initial:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "4000:5432"
